language: objective-c
# cache: cocoapods
before_install:
- gem install cocoapods
# - pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild build -workspace Example/Forgeries.xcworkspace -scheme Forgeries-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
after_success: bundle exec slather
